proto_outdir = "./third_party/proto"

[[dependencies]]
    target = "github.com/medibloc/panacea-core/proto"
    revision = "v2.0.0"

[[dependencies]]
    target = "github.com/cosmos/cosmos-sdk/third_party/proto"
    revision = "v0.42.7"

[[dependencies]]
    target = "github.com/cosmos/cosmos-sdk/proto"
    revision = "v0.42.7"


