# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches:    # only for pushes on master
    - master
  pull_request:  # for all PRs regardless of its base branch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Run a panacea-core docker container
      env:
        CHAIN_ID: testing
        MNEMONIC: bulb rail shoot abandon eye domain injury return dash away base retreat vote solve recall glass joy neck cabin volcano enemy tribe output nominee
      run: |
        docker run --rm -d \
          -e CHAIN_ID="${CHAIN_ID}" \
          -e MNEMONIC="${MNEMONIC}" \
          -p 26657:26657 \
          -v $(pwd)/scripts:/root/scripts \
          --name core \
          ghcr.io/medibloc/panacea-core:master \
          bash /root/scripts/panacea-core/init.sh

    - name: Run tests
      env:
        PANACEAD_ENABLED: true
      run: yarn test
