# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches: # only for pushes on master
      - master
  pull_request: # for all PRs regardless of its base branch

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      CHAIN_ID: testing
      MNEMONIC: ${{ secrets.TEST_MNEMONIC }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run tests
        env:
          PANACEAD_ENABLED: true
        run: yarn test
